// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwr0314_8_xdwld5QUnaT8OCiG3XqF5b0',
    appId: '1:895998651231:web:5aa024e93ae8f92cb7a4ea',
    messagingSenderId: '895998651231',
    projectId: 'bankpick',
    authDomain: 'bankpick.firebaseapp.com',
    storageBucket: 'bankpick.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZpyiXrSmy7pMdm_s5VAbmLZgOolCYlWk',
    appId: '1:895998651231:android:a79a815d8a573617b7a4ea',
    messagingSenderId: '895998651231',
    projectId: 'bankpick',
    storageBucket: 'bankpick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA72-KZKXfzpUbb-ydZTfIJ3LDinuuozSo',
    appId: '1:895998651231:ios:d26411ffdc5f6ab7b7a4ea',
    messagingSenderId: '895998651231',
    projectId: 'bankpick',
    storageBucket: 'bankpick.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA72-KZKXfzpUbb-ydZTfIJ3LDinuuozSo',
    appId: '1:895998651231:ios:d26411ffdc5f6ab7b7a4ea',
    messagingSenderId: '895998651231',
    projectId: 'bankpick',
    storageBucket: 'bankpick.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwr0314_8_xdwld5QUnaT8OCiG3XqF5b0',
    appId: '1:895998651231:web:1be16798d69678b1b7a4ea',
    messagingSenderId: '895998651231',
    projectId: 'bankpick',
    authDomain: 'bankpick.firebaseapp.com',
    storageBucket: 'bankpick.firebasestorage.app',
  );
}
